# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
import numpy as np
arr1 = np.random.randint(1, 21, (5,5))
arr1[:,2] = 1
arr1

array([[18,  1,  1, 14, 15],
       [16, 13,  1,  3, 20],
       [ 1, 11,  1, 14, 12],
       [10, 19,  1, 10, 19],
       [15,  6,  1,  5, 20]])

In [4]:
arr2 = np.random.randint(1,17,(4,4))
np.fill_diagonal(arr2,0)
arr2

array([[ 0,  5, 14,  7],
       [ 6,  0, 15, 13],
       [ 7, 10,  0,  1],
       [ 9,  4, 16,  0]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:

import numpy as np

# Create a NumPy array of shape (6, 6) with values from 1 to 36
arr = np.arange(1, 37).reshape(6, 6)

# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns
sub_array = arr[2:5, 1:4]

sub_array


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [6]:

import numpy as np

# Create a NumPy array of shape (5, 5) with random integers between 1 and 20
arr = np.random.randint(1, 21, (5, 5))

# Extract the elements on the border
border_elements = np.concatenate([arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]])

border_elements


array([14,  1,  2,  8, 18, 19,  4, 20, 11,  7, 17,  9, 20, 18,  3, 19])

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [8]:

import numpy as np

# Create two NumPy arrays of shape (3, 4) filled with random integers between 1 and 10
arr1 = np.random.randint(1, 11, (3, 4))
arr2 = np.random.randint(1, 11, (3, 4))

# Perform element-wise addition
add_result = arr1 + arr2

# Perform element-wise subtraction
sub_result = arr1 - arr2

# Perform element-wise multiplication
mul_result = arr1 * arr2

# Perform element-wise division (avoid division by zero)
div_result = np.divide(arr1, arr2, where=arr2 != 0)

arr1, arr2, add_result, sub_result, mul_result, div_result


(array([[1, 9, 9, 3],
        [5, 2, 8, 2],
        [2, 1, 9, 5]]),
 array([[ 3,  8,  4,  5],
        [ 1,  7,  3, 10],
        [ 9,  7,  1,  8]]),
 array([[ 4, 17, 13,  8],
        [ 6,  9, 11, 12],
        [11,  8, 10, 13]]),
 array([[-2,  1,  5, -2],
        [ 4, -5,  5, -8],
        [-7, -6,  8, -3]]),
 array([[ 3, 72, 36, 15],
        [ 5, 14, 24, 20],
        [18,  7,  9, 40]]),
 array([[0.33333333, 1.125     , 2.25      , 0.6       ],
        [5.        , 0.28571429, 2.66666667, 0.2       ],
        [0.22222222, 0.14285714, 9.        , 0.625     ]]))

In [9]:

# Create a NumPy array of shape (4, 4) with values from 1 to 16
arr3 = np.arange(1, 17).reshape(4, 4)

# Compute the row-wise sum
row_sum = arr3.sum(axis=1)

# Compute the column-wise sum
col_sum = arr3.sum(axis=0)

arr3, row_sum, col_sum


(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([10, 26, 42, 58]),
 array([28, 32, 36, 40]))

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [12]:


import numpy as np

# Create a NumPy array of shape (5, 5) filled with random integers between 1 and 100
arr1 = np.random.randint(1, 101, (5, 5))

# Compute the mean
mean = np.mean(arr1)

# Compute the median
median = np.median(arr1)

# Compute the standard deviation
std_dev = np.std(arr1)

# Compute the variance
variance = np.var(arr1)

arr1, mean, median, std_dev, variance




(array([[45, 34, 15, 37, 94],
        [71, 49, 50, 90, 75],
        [91, 61, 63,  9, 12],
        [21, 94,  3, 58, 80],
        [63, 60, 35, 81, 12]]),
 52.12,
 58.0,
 28.362397641948398,
 804.4256)

In [ ]:

#Create a NumPy array of shape (3, 3) with values from 1 to 9
arr2 = np.arange(1, 10).reshape(3, 3)

# Normalize the array (scale to have mean 0 and standard deviation 1)
normalized_arr = (arr2 - np.mean(arr2)) / np.std(arr2)

arr2, normalized_arr



### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


In [ ]:

import numpy as np

# Create a NumPy array of shape (3, 3) filled with random integers between 1 and 10
arr_2d = np.random.randint(1, 11, (3, 3))

# Create a 1D array of shape (3,)
arr_1d = np.array([1, 2, 3])

# Add the 1D array to each row of the 2D array using broadcasting
result_add = arr_2d + arr_1d

arr_2d, arr_1d, result_add


In [ ]:

# Create a NumPy array of shape (4, 4) filled with random integers between 1 and 10
arr_2d_4x4 = np.random.randint(1, 11, (4, 4))

# Create a 1D array of shape (4,)
arr_1d_4 = np.array([1, 2, 3, 4])

# Subtract the 1D array from each column of the 2D array using broadcasting
result_subtract = arr_2d_4x4 - arr_1d_4

arr_2d_4x4, arr_1d_4, result_subtract



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [ ]:

import numpy as np

# Create a NumPy array of shape (3, 3) representing a matrix
matrix_3x3 = np.random.randint(1, 11, (3, 3))

# Compute the determinant
determinant = np.linalg.det(matrix_3x3)

# Compute the inverse (only if the determinant is non-zero)
if determinant != 0:
    inverse = np.linalg.inv(matrix_3x3)
else:
    inverse = None

# Compute the eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(matrix_3x3)

matrix_3x3, determinant, inverse, eigenvalues


In [ ]:

# Create two NumPy arrays
arr1 = np.random.randint(1, 11, (2, 3))  # Shape (2, 3)
arr2 = np.random.randint(1, 11, (3, 2))  # Shape (3, 2)

# Perform matrix multiplication
result_multiplication = np.dot(arr1, arr2)

arr1, arr2, result_multiplication


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [ ]:

import numpy as np

# Create a NumPy array of shape (3, 3) with values from 1 to 9
arr_3x3 = np.arange(1, 10).reshape(3, 3)

# Reshape the array to shape (1, 9)
reshaped_1x9 = arr_3x3.reshape(1, 9)

# Reshape the array to shape (9, 1)
reshaped_9x1 = arr_3x3.reshape(9, 1)

arr_3x3, reshaped_1x9, reshaped_9x1


In [ ]:

# Create a NumPy array of shape (5, 5) filled with random integers between 1 and 100
arr_5x5 = np.random.randint(1, 101, (5, 5))

# Flatten the array
flattened_arr = arr_5x5.flatten()

# Reshape it back to shape (5, 5)
reshaped_5x5 = flattened_arr.reshape(5, 5)

arr_5x5, flattened_arr, reshaped_5x5


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [13]:

import numpy as np

# Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20
arr_5x5 = np.random.randint(1, 21, (5, 5))

# Use fancy indexing to extract the elements at the corners of the array
corners = arr_5x5[[0, 0, -1, -1], [0, -1, 0, -1]]

arr_5x5, corners


(array([[ 2,  3,  4,  8, 18],
        [17, 13, 16,  2, 10],
        [13,  1, 15, 20, 10],
        [13,  5,  4, 20, 14],
        [ 7,  2, 12,  5,  2]]),
 array([ 2, 18,  7,  2]))

In [ ]:

# Create a NumPy array of shape (4, 4) filled with random integers between 1 and 20
arr_4x4 = np.random.randint(1, 21, (4, 4))

# Use boolean indexing to set all elements greater than 10 to 10
arr_4x4[arr_4x4 > 10] = 10

arr_4x4


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [ ]:

import numpy as np

# Define a structured array with fields 'name', 'age', and 'weight'
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

# Create some sample data
data = [
    ('vishnu', 25, 55.5),
    ('shiva', 30, 75.2),
    ('krishna', 20, 65.3),
    ('ram', 25, 85.0)
]

# Create the structured array
structured_arr = np.array(data, dtype=dtype)

# Sort the array by 'age' field
sorted_arr = np.sort(structured_arr, order='age')

structured_arr, sorted_arr


In [ ]:

# Define a structured array with fields 'x' and 'y'
dtype_points = [('x', 'i4'), ('y', 'i4')]

# Create some sample points data
points_data = [
    (1, 2),
    (4, 6),
    (7, 8),
    (2, 1)
]

# Create the structured array for points
points_arr = np.array(points_data, dtype=dtype_points)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt(
    (points_arr['x'][:, np.newaxis] - points_arr['x'])**2 + 
    (points_arr['y'][:, np.newaxis] - points_arr['y'])**2
)

points_arr, distances


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:

import numpy as np
import numpy.ma as ma

# Create a 4x4 array of random integers between 1 and 20
arr_4x4 = np.random.randint(1, 21, (4, 4))

# Mask the elements greater than 10
masked_arr = ma.masked_where(arr_4x4 > 10, arr_4x4)

# Compute the sum of the unmasked elements
sum_unmasked = masked_arr.sum()

arr_4x4, masked_arr, sum_unmasked


In [ ]:
# %%
# Create a 3x3 array of random integers between 1 and 20
arr_3x3 = np.random.randint(1, 21, (3, 3))

# Mask the diagonal elements
masked_diag = ma.masked_array(arr_3x3, mask=np.eye(3, dtype=bool))

# Compute the mean of the unmasked elements
mean_unmasked = masked_diag.mean()

# Replace the masked diagonal elements with the mean of the unmasked elements
masked_diag_filled = masked_diag.filled(mean_unmasked)

arr_3x3, masked_diag, mean_unmasked, masked_diag_filled
