In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:

import numpy as np
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
#two 2d array
import numpy as np
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
arr2.shape

(2, 5)

In [15]:
import numpy as np
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4)) #one's function with 3 rows and 4 columns.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
arr = np.array([[1, 2, 3,], [4, 5, 6]])
print('Array:\n', arr)
print('shape', arr.shape)
print('number of dimensions:', arr.ndim)
print('size(number of elements):', arr.size)
print('Data type:', arr.dtype)


Array:
 [[1 2 3]
 [4 5 6]]
shape (2, 3)
number of dimensions: 2
size(number of elements): 6
Data type: int64


In [22]:
#Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#element addition
print('addition:', arr1+arr2)

#element substraction
print('substraction:', arr1-arr2)

#element multiplication
print('multiplication:', arr1 * arr2)

#

addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]


In [25]:
#universall functions
arr = np.array([2,3,4,5,6])
##square root
print(np.sqrt(arr))
print(np.exp(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


In [27]:
#array slicing and indexing 
arr=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('Array: \n', arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
arr[0][1] #first row index then column index
#pick 7 8 11 and 12 elements
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [46]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [47]:
arr[1:]=[100]
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]
